// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidate3Response struct {
	ContentType                     string
	PostValidate3200TextPlainObject *string
	StatusCode                      int
	RawResponse                     *http.Response
}

func (o *PostValidate3Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidate3Response) GetPostValidate3200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate3200TextPlainObject
}

func (o *PostValidate3Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidate3Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
