// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidate11Response struct {
	ContentType                      string
	PostValidate11200TextPlainObject *string
	StatusCode                       int
	RawResponse                      *http.Response
}

func (o *PostValidate11Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidate11Response) GetPostValidate11200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate11200TextPlainObject
}

func (o *PostValidate11Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidate11Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
