// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidateResponse struct {
	ContentType                    string
	PostValidate200TextPlainObject *string
	StatusCode                     int
	RawResponse                    *http.Response
}

func (o *PostValidateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidateResponse) GetPostValidate200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate200TextPlainObject
}

func (o *PostValidateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
