// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidate4Response struct {
	ContentType                     string
	PostValidate4200TextPlainObject *string
	StatusCode                      int
	RawResponse                     *http.Response
}

func (o *PostValidate4Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidate4Response) GetPostValidate4200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate4200TextPlainObject
}

func (o *PostValidate4Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidate4Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
