// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidate1Response struct {
	ContentType                     string
	PostValidate1200TextPlainObject *string
	StatusCode                      int
	RawResponse                     *http.Response
}

func (o *PostValidate1Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidate1Response) GetPostValidate1200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate1200TextPlainObject
}

func (o *PostValidate1Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidate1Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
