// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostValidate12Response struct {
	// HTTP response content type for this operation
	ContentType                      string
	PostValidate12200TextPlainObject *string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostValidate12Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostValidate12Response) GetPostValidate12200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.PostValidate12200TextPlainObject
}

func (o *PostValidate12Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostValidate12Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
