// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ValidateResponse struct {
	ContentType                string
	StatusCode                 int
	RawResponse                *http.Response
	Validate200TextPlainObject *string
}

func (o *ValidateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ValidateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ValidateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ValidateResponse) GetValidate200TextPlainObject() *string {
	if o == nil {
		return nil
	}
	return o.Validate200TextPlainObject
}
