// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/oneof-v1/pkg/utils"
)

type ArrayOfCatOrDogObjectsValueType string

const (
	ArrayOfCatOrDogObjectsValueTypeCat ArrayOfCatOrDogObjectsValueType = "Cat"
	ArrayOfCatOrDogObjectsValueTypeDog ArrayOfCatOrDogObjectsValueType = "Dog"
)

type ArrayOfCatOrDogObjectsValue struct {
	Cat *Cat
	Dog *Dog

	Type ArrayOfCatOrDogObjectsValueType
}

func CreateArrayOfCatOrDogObjectsValueCat(cat Cat) ArrayOfCatOrDogObjectsValue {
	typ := ArrayOfCatOrDogObjectsValueTypeCat

	return ArrayOfCatOrDogObjectsValue{
		Cat:  &cat,
		Type: typ,
	}
}

func CreateArrayOfCatOrDogObjectsValueDog(dog Dog) ArrayOfCatOrDogObjectsValue {
	typ := ArrayOfCatOrDogObjectsValueTypeDog

	return ArrayOfCatOrDogObjectsValue{
		Dog:  &dog,
		Type: typ,
	}
}

func (u *ArrayOfCatOrDogObjectsValue) UnmarshalJSON(data []byte) error {

	cat := new(Cat)
	if err := utils.UnmarshalJSON(data, &cat, "", true, true); err == nil {
		u.Cat = cat
		u.Type = ArrayOfCatOrDogObjectsValueTypeCat
		return nil
	}

	dog := new(Dog)
	if err := utils.UnmarshalJSON(data, &dog, "", true, true); err == nil {
		u.Dog = dog
		u.Type = ArrayOfCatOrDogObjectsValueTypeDog
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ArrayOfCatOrDogObjectsValue) MarshalJSON() ([]byte, error) {
	if u.Cat != nil {
		return utils.MarshalJSON(u.Cat, "", true)
	}

	if u.Dog != nil {
		return utils.MarshalJSON(u.Dog, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// ArrayOfCatOrDogObjects - Case 4
type ArrayOfCatOrDogObjects struct {
	Value []ArrayOfCatOrDogObjectsValue
}

func (o *ArrayOfCatOrDogObjects) GetValue() []ArrayOfCatOrDogObjectsValue {
	if o == nil {
		return []ArrayOfCatOrDogObjectsValue{}
	}
	return o.Value
}
