// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Cat struct {
	Meows bool
}

func (o *Cat) GetMeows() bool {
	if o == nil {
		return false
	}
	return o.Meows
}
