// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/oneof-v1/pkg/utils"
)

type CatOrDogValueType string

const (
	CatOrDogValueTypeCat CatOrDogValueType = "Cat"
	CatOrDogValueTypeDog CatOrDogValueType = "Dog"
)

type CatOrDogValue struct {
	Cat *Cat
	Dog *Dog

	Type CatOrDogValueType
}

func CreateCatOrDogValueCat(cat Cat) CatOrDogValue {
	typ := CatOrDogValueTypeCat

	return CatOrDogValue{
		Cat:  &cat,
		Type: typ,
	}
}

func CreateCatOrDogValueDog(dog Dog) CatOrDogValue {
	typ := CatOrDogValueTypeDog

	return CatOrDogValue{
		Dog:  &dog,
		Type: typ,
	}
}

func (u *CatOrDogValue) UnmarshalJSON(data []byte) error {

	cat := Cat{}
	if err := utils.UnmarshalJSON(data, &cat, "", true, true); err == nil {
		u.Cat = &cat
		u.Type = CatOrDogValueTypeCat
		return nil
	}

	dog := Dog{}
	if err := utils.UnmarshalJSON(data, &dog, "", true, true); err == nil {
		u.Dog = &dog
		u.Type = CatOrDogValueTypeDog
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CatOrDogValue) MarshalJSON() ([]byte, error) {
	if u.Cat != nil {
		return utils.MarshalJSON(u.Cat, "", true)
	}

	if u.Dog != nil {
		return utils.MarshalJSON(u.Dog, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// CatOrDog - Case 1
type CatOrDog struct {
	Value CatOrDogValue
}

func (o *CatOrDog) GetValue() CatOrDogValue {
	if o == nil {
		return CatOrDogValue{}
	}
	return o.Value
}
