// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/speakeasy-sdks/oneof-v1/pkg/utils"
)

type CatsOrDogsValueType string

const (
	CatsOrDogsValueTypeArrayOfCat CatsOrDogsValueType = "arrayOfCat"
	CatsOrDogsValueTypeArrayOfDog CatsOrDogsValueType = "arrayOfDog"
)

type CatsOrDogsValue struct {
	ArrayOfCat []Cat
	ArrayOfDog []Dog

	Type CatsOrDogsValueType
}

func CreateCatsOrDogsValueArrayOfCat(arrayOfCat []Cat) CatsOrDogsValue {
	typ := CatsOrDogsValueTypeArrayOfCat

	return CatsOrDogsValue{
		ArrayOfCat: arrayOfCat,
		Type:       typ,
	}
}

func CreateCatsOrDogsValueArrayOfDog(arrayOfDog []Dog) CatsOrDogsValue {
	typ := CatsOrDogsValueTypeArrayOfDog

	return CatsOrDogsValue{
		ArrayOfDog: arrayOfDog,
		Type:       typ,
	}
}

func (u *CatsOrDogsValue) UnmarshalJSON(data []byte) error {

	arrayOfCat := []Cat{}
	if err := utils.UnmarshalJSON(data, &arrayOfCat, "", true, true); err == nil {
		u.ArrayOfCat = arrayOfCat
		u.Type = CatsOrDogsValueTypeArrayOfCat
		return nil
	}

	arrayOfDog := []Dog{}
	if err := utils.UnmarshalJSON(data, &arrayOfDog, "", true, true); err == nil {
		u.ArrayOfDog = arrayOfDog
		u.Type = CatsOrDogsValueTypeArrayOfDog
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CatsOrDogsValue) MarshalJSON() ([]byte, error) {
	if u.ArrayOfCat != nil {
		return utils.MarshalJSON(u.ArrayOfCat, "", true)
	}

	if u.ArrayOfDog != nil {
		return utils.MarshalJSON(u.ArrayOfDog, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// CatsOrDogs - Case 2
type CatsOrDogs struct {
	Value CatsOrDogsValue
}

func (o *CatsOrDogs) GetValue() CatsOrDogsValue {
	if o == nil {
		return CatsOrDogsValue{}
	}
	return o.Value
}
