// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Dog struct {
	Barks bool
}

func (o *Dog) GetBarks() bool {
	if o == nil {
		return false
	}
	return o.Barks
}
