// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Wolf struct {
	Howls bool
}

func (o *Wolf) GetHowls() bool {
	if o == nil {
		return false
	}
	return o.Howls
}
